### ISSUE TITLE
mnl.so not found at runtime

### ISSUE THREAD

**Issue by egeldenhuys** [RagingGrim/mnl#3]
```
g++ hash-crack.cpp mnl.so -lpthread -lcrypto
```

```
./a.out: error while loading shared libraries: mnl.so: cannot open shared object file: No such file or directory
```

Solution:
```
g++ hash-crack.cpp mnl.so -lpthread -lcrypto -Wl,-rpath='$$ORIGIN'
```

http://stackoverflow.com/questions/6562403/i-dont-understand-wl-rpath-wl

**Comment by RagingGrim** [comment]
This is because I am using compiling mnl as a shared library. 

I will in a future release add a target for both compiling as a shared library and compiling as a static library with the latter being the default.

Thanks!

**Comment by RagingGrim** [comment]
Use `make static` to generate a static version of the library

When using `make dynamic` you have to copy the generated .so file into /usr/lib/
